### ISSUE TITLE
New folder added in `src` not picked up by `make deploy`

### ISSUE THREAD

**Issue by Sakrecoer** [dyne/docs#1]
This is amazing! Thank you very much!

I somehow fail to get it to work, as the Makefile doesn't pick up new folders in `src`. I tried runing `make all` first to see if that had any effect. It did list the content correctly, but had no effect on `make deploy`.

My Makefile-fu is awfully limited, but i think it might have to do with [line1](https://github.com/dyne/docs/blob/1cfe65869d4875e8415a554da8a221a7ca155814/Makefile#L1) which specifically lists `jaromail`. I'm not sure how to make it pick up a variable though...

**Comment by jaromil** [comment]
Yes! forgot in the docs... so the folder needs to be listed also in the Makefile for now, first line...

**Comment by Sakrecoer** [comment]
that fixed it `\o/` will amend the read me before i close the issue

**Comment by jaromil** [comment]
meanwhile I fixed the makefile to not require that and updated the readme.
