### ISSUE TITLE
Complete with screenshots

### ISSUE THREAD

**Issue by jaromil** [dyne/docs#2]
Manuals can really benefit from having some more screenshots.

It may be easier to add them by editing on github from its web editor, which accepts cut & paste actions and uploads them to github assets: haven't tried yet myself, but in theory should work.

**Comment by Sakrecoer** [comment]
Sadly the images aren't uploaded to the repo, so it makes migration harder, but this is a good intermediary solution. Note that mkdocs Material theme uses a [specific format](https://squidfunk.github.io/mkdocs-material/reference/images/) that allows image formatting, which can be desired in many situations, i.e. captions:
https://squidfunk.github.io/mkdocs-material/reference/images/#image-captions

**Comment by jaromil** [comment]
ok, then load images. will look for an editor to ease cut & paste.
